### ISSUE TITLE
What does FEE stand for?

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/fontFeatures#2]
The people want to know!

[Text Shaping Working Group Proposal TSWG 2020-01: Shaping Ideographic Description Sequences](https://docs.google.com/document/d/1NYKsNOjkOamIRdfMReZfxAhtOUMiHNm_TIidb0Daob4/edit?usp=sharing) (see page 4)

**Comment by simoncozens** [comment]
Font Engineering (with) Extensibility. Leaving issue open because it needs documentation to explain this...

**Comment by simoncozens** [comment]
Now documented.
