### ISSUE TITLE
ValueRecord device records

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/fontFeatures#31]
Currently we don't support them. And with variable fonts, we kind of need to. It's kind of hard to know what to do with them.

* Old-style ppem adjustment device records: we should probably store the delta array when we read in an OTF file in GPOSUnparser. But what can we actually do with it when we've got it? We can't express it in Adobe FEA syntax because Value Record Format C is "currently unimplemented". But at least if it *were* to be implemented, we would be able to express it and emit it.
* New-style VariationIndex device records: We should probably read these into our multiple-master-style value records. But there's *absolutely* no way to do anything sensible with them in FEA.

We really need our own binary emitter.

**Comment by anthrotype** [comment]
> We really need our own binary emitter.

why?

**Comment by simoncozens** [comment]
Well, precisely for this reason. There's currently no way to emit a positioning rule with variation deltas using FEA.

**Comment by justvanrossum** [comment]
Is this still true, with the variations-in-fea extensions?

**Comment by justvanrossum** [comment]
That's cool, thanks.

What about the reverse, for otf2fea? I don't see that happening, and am trying to find out to what extent this is expected or not.

**Comment by simoncozens** [comment]
It probably should happen but I haven't implemented it. :-/

**Comment by justvanrossum** [comment]
No problem, and thanks for clearing that up!

**Comment by justvanrossum** [comment]
Would you accept a contribution that outputs variable scalars in .fea for otf2fea? Not promising anything (I haven't investigated how to do it), but I'm still interested in the functionality. Or maybe: is there equivalent Rust functionality out there?

**Comment by simoncozens** [comment]
There will be equivalent Rust functionality by the end of this week.

**Comment by simoncozens** [comment]
(But also yes, sure!)

**Comment by justvanrossum** [comment]
For my purposes, a black box that I can feed otf data and gives me .fea in return would be ideal.
