### ISSUE TITLE
Don't access OnlineVarStoreBuilder internals

### ISSUE THREAD

**Issue by behdad** [simoncozens/fontFeatures#39]
https://github.com/simoncozens/fontFeatures/blob/9d475a0825c06d1f4da28f76a262d6bba064a236/fontFeatures/ttLib/FontFeatures.py#L16-L25

Instead of accessing `varstorebuilder._varDataIndices`, let's add a method to either the builder or the resulting VariatinoStore to do what you want.

Making `.finish()` return `None` if the store is empty sounds like the better fix to me.

**Comment by behdad** [comment]
> Making `.finish()` return `None` if the store is empty sounds like the better fix to me.

I wish I had done it that way before. But that change now would constitute an API break. Here's how we do the check in varLib itself:
```
        store = merger.store_builder.finish()
        if not store.VarData:
                return
```

**Comment by simoncozens** [comment]
Ok, I’ll check that. Related issue: what does the store builder do when all deltas are zero?  (No variation.) I could probably detect that myself but I’m lazy. If there’s an easy way to detect it, and have the returned index be None or something, that would be a helpful optimisation. Currently I just make a device table in all cases, which is probably not optimal.

**Comment by behdad** [comment]
Okay, opened fonttools issue to address both.
