### ISSUE TITLE
A Vim syntax highlighting file for FEE language would be nice

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/fontFeatures#4]

**Comment by simoncozens** [comment]
I like the idea but given that plugins can change the grammar...

**Comment by ctrlcctrlv** [comment]
Not the end of the road by any means IMO

I'd expect most plugins to follow similar grammar rules, and since there aren't many users yet, only default plugins in most common use. Popular plugins, if they ever exist, can get written into the Vim grammar, right? :)
