### ISSUE TITLE
otf2fea outputs UTF-16 little-endian with BOM

### ISSUE THREAD

**Issue by bdenckla** [simoncozens/fontFeatures#41]
On Windows at least.  Because of this, FontForge won't import otf2fea's output. One could say that this is a bug (or missing feature) in FontForge, not otf2fea, but... this is IMO a somewhat obscure text format to use... seems like UTF-8 without BOM is more of a standard, right?

No big deal, I can just convert the format myself, but it would be more convenient to not have to.

**Comment by simoncozens** [comment]
Hmm. Agree it should be UTF8 (as feature filters should be ASCII!). Doesn’t Windows Python >3.6 emit UTF8 by default?

https://vstinner.github.io/python36-utf8-windows.html

**Comment by bdenckla** [comment]
This is Python 3.8.9 so it seems like something must be somewhat explicitly asking for UTF-16 LE w/BOM.

**Comment by bdenckla** [comment]
See .zip file attached to #44 for a concrete example.
