### ISSUE TITLE
otf2fea --gdef always lists nonmarkingreturn?

### ISSUE THREAD

**Issue by bdenckla** [simoncozens/fontFeatures#42]
nonmarkingreturn is not a glyph name in my font.

In fact the name nonmarkingreturn is a little confusing/nonstandard: some superficial Googling suggests maybe controlCR is the AGL name?

**Comment by bdenckla** [comment]
See .zip file attached to #44 for a concrete example.

**Comment by simoncozens** [comment]
nonmarkingreturn is glyph ID 2 in the font you provided. It's not in the AGL, but it is in the list of [Macintosh standard glyphs](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html).

**Comment by bdenckla** [comment]
Sorry for my confusion. It turns out this `nonmarkingreturn` glyph is created _ex nihilo_ when FontForge generates the `.ttf`. So naturally `nonmarkingreturn` appears in a `.fea` file decompiled from the `.ttf` by `otf2fea`. And naturally when I asked FontForge to import (merge) that `.fea` file  into a "featureless" (glyphs-only) version of the font, FontForge complained about `nonmarkingreturn` not existing, which is what caused me to raise this (non-)issue!

What's more, I've now become aware that not only is `nonmarkingreturn` created _ex nihilo_, also glyphs are renumbered, i.e. glyph IDs change from what appears in the `.sfd` (FontForge) sources to what appears in the generated `.ttf`. For example, in the `.sfd` sources, the glyph named `space` has ID 2 (last of the 3 numbers on the `Encoding:` line):

```
StartChar: space
Encoding: 1 32 2
Width: 682
GlyphClass: 2
Flags: W
LayerCount: 2
EndChar
```
But in an `.sfd` decompiled from the generated `.ttf`, we can see that not only was `nonmarkingreturn` created _ex nihilo_, it also "took" ID 2 from `space`, with `space` being displaced to ID 3:
```
StartChar: nonmarkingreturn
Encoding: 65537 -1 2
Width: 682
GlyphClass: 2
Flags: W
LayerCount: 2
EndChar

StartChar: space
Encoding: 32 32 3
Width: 682
GlyphClass: 2
Flags: W
LayerCount: 2
EndChar
```
