### ISSUE TITLE
otf2fea emits empty statements

### ISSUE THREAD

**Issue by bdenckla** [simoncozens/fontFeatures#43]
E.g. 
```
lookupflag RightToLeft;
;
```
This may well be legal feature-language syntax, but it upsets FontForge, so it might be nice to suppress such empty statements.

**Comment by bdenckla** [comment]
See .zip file attached to #44 for a concrete example.

**Comment by simoncozens** [comment]
Hm. No, sorry, FontForge is in the wrong here. There's a spec for the feature language, and this is allowed.

**Comment by bdenckla** [comment]
Fair enough. I am considering moving away from FontForge for other reasons, but even if I want to stay with FontForge, it is easy for me to remove these empty statements with a search & replace (manual or scripted), so that's another reason (in addition to their legality) to not worry about these empty statements. I.e. there is a not-to-painful workaround.
