### ISSUE TITLE
Missing "MarkToBase*" routine name in GPOS lookup type 4 fontTools.ttLib.TTFont unparse

### ISSUE THREAD

**Issue by chrissimpkins** [simoncozens/fontFeatures#45]
macOS 10.15.7
cPython 3.9.5
fontFeatures lib version 1.0.5, PyPI install

I am trying to filter the GPOS type 4 lookups by `MarkToBase` string prefix in the routine name key.  When I attempted this with Montserrat-Regular.ttf, I came across a type 4 lookup that has an empty name string. This caused it to slip through this filter (and lots of head banging to figure out why I couldn't locate expected bases/marks...).

Repro:

```python
import sys

import fontFeatures
from fontTools.ttLib import TTFont


def main(argv):

    for fontpath in argv:
        tt = TTFont(fontpath)
        ff = fontFeatures.ttLib.unparse(tt)

        mark2base_routines = [
            routine for routine in ff.routines if routine.name.startswith("MarkToBase")
        ]

        empty_name_routines = [routine for routine in ff.routines if routine.name == ""]

        print(f"Total routine number: {len(ff.routines)}")
        # Expected 3 Lookup Type 4 routines in Montserrat-Regular.ttf
        print(f"Routines with MarkToBase* names: {len(mark2base_routines)}")
        print(f"Empty name routines: {empty_name_routines}")
        if len(empty_name_routines) > 0:
            print(f"Example empty name routine: {empty_name_routines[0].__dict__}")


if __name__ == "__main__":
    main(sys.argv[1:])
```

with:

[Montserrat-Regular.ttf.zip](https://github.com/simoncozens/fontFeatures/files/6517828/Montserrat-Regular.ttf.zip)

Output:

```
Total routine number: 53
Routines with MarkToBase* names: 2
Empty name routines: [<fontFeatures.Routine object at 0x107f47df0>]
Example empty name routine: {'name': '', 'usecount': 0, 'usedin': set(), 'rules': [<fontFeatures.Attachment object at 0x1105f7820>, <fontFeatures.Attachment object at 0x1105f7970>, <fontFeatures.Attachment object at 0x1105f79a0>, <fontFeatures.Attachment object at 0x1105f79d0>, <fontFeatures.Attachment object at 0x1105f7a00>], 'address': None, 'comments': [], 'inlined': False, 'languages': [('DFLT', 'dflt'), ('cyrl', 'dflt'), ('latn', 'dflt')], 'parent': None, 'flags': 0, 'markFilteringSet': None, 'markAttachmentSet': None}
```

Is there a better way to filter by lookup type?

**Comment by chrissimpkins** [comment]
<img width="1768" alt="2021-05-20_13-53-51" src="https://user-images.githubusercontent.com/4249591/119026380-18992780-b973-11eb-9d47-b102e93494c5.png">

**Comment by chrissimpkins** [comment]
This seems to be detected as an ExtensionRoutine and there the lack of a name definition is due to instantiation without a name parameter @ https://github.com/simoncozens/fontFeatures/blob/b85039ebe903efdd39b77c4d44608dfe40b41806/fontFeatures/ttLib/GTableUnparser.py#L217

I can modify it as follows:

```python
    def unparseExtension(self, lookup):
        """Handles extension lookups by recursing into them."""
        routines = []
        dependencies = []
        for xt in lookup.SubTable:
            xt.SubTable = [xt.ExtSubTable]
            xt.LookupType = xt.ExtSubTable.LookupType
            xt.LookupFlag = lookup.LookupFlag
            routine, deps = self.unparseLookup(xt, self.currentLookup)
            routines.append(routine)
            dependencies.extend(deps)
            # print(routine.name)
        extension = fontFeatures.ExtensionRoutine(
            routines=routines, name=self.getname("Extension" + self.gensym())
        )
        return extension, dependencies
```

and it shows up with the prefix string "Extension*".  I can then identify it as an Extension routine type and iterate through the rules. But I don't have any context about the lookup type for the routines contained in the ExtensionRoutine.  Is it possible to define the lookup type names as these routines are flattened?  Or perhaps a lookup_type integer value as a Routine obj attribute?

**Comment by simoncozens** [comment]
No, rules in an extension must all be the same type. You can check if they are instances of Attach and then check if they contain the mark/base you’re looking for.

**Comment by chrissimpkins** [comment]
Worth a small PR to add the "Extension" + number name scheme on these routines?

**Comment by simoncozens** [comment]
Yes please!

**Comment by chrissimpkins** [comment]
https://github.com/simoncozens/fontFeatures/pull/46

**Comment by chrissimpkins** [comment]
I will open a new one with just the extension name mod
