### ISSUE TITLE
Include should be able to also include FEA files. IncludeFEA?

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/fontFeatures#9]
I don't know if I'll have time to contribute one

**Comment by simoncozens** [comment]
I'm working on something else today, but here's how I would look at it:

* Choose some *really obvious* delimiters to avoid having to do nasty parsing work.
* Subclass fontFeatures.feaParser, and override the `__init__` routine to take an existing fontFeatures object.
* Pass the content of the parsed string to the new subclass, and ...done, I guess?

**Comment by ctrlcctrlv** [comment]
Actually I'm not so in love with this anymore due to delimiters. I think that it's better to just add an `IncludeFEA` verb to `feeLib/Include.py` and will update issue topic accordingly.
